name: Code Check

on:
  push:
    branches:
      - '**'       # Alle Branches
  pull_request:
    branches:
      - '**'       # Alle Branches

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"  # oder deine Python-Version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run flake8 (Linting)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run black check (Formatting)
      run: |
        black --check .
