# .github/workflows/label.yml

name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    # Schritt 1: Fügt den Checkout-Schritt hinzu, um die Dateien lokal abzurufen
    - uses: actions/checkout@v4 

    # Schritt 2: Führt den Labeler aus.
    - uses: actions/labeler@v5
      with:
        # configuration-path ist jetzt optional, aber sicherheitshalber belassen wir ihn
        configuration-path: .github/labels.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
