# .github/workflows/label.yml

name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    # 1. Fügt den Checkout-Schritt hinzu, um sicherzustellen, 
    #    dass die Dateien, einschließlich labeler.yml, lokal vorhanden sind.
    - uses: actions/checkout@v4 

    # 2. Führt den Labeler aus.
    - uses: actions/labeler@v5
      with:
        # Dies ist jetzt optional, aber gut zur Sicherheit.
        configuration-path: .github/labeler.yml
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
